config/routes.rb
DebugApp::Application.routes.draw do
  resources :beermaps

end

app/models/beermap.rb
class Beermap < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#  Garb::Session.login("vikas@connect4fitness.com", "sun12sun")
 # profile = Garb::Management::Profile.all.detect {|p| p.web_property_id == 'UA-XXXXXXX-X'}
  protect_from_forgery
end

app/controllers/beermaps_controller.rb
require 'beer_mapping'
require 'twilio-ruby'
class BeermapsController < ApplicationController
  # GET /beermaps
  # GET /beermaps.json
  def index
    @beermaps = Beermap.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beermaps }
    end
    
    beer = BeerMapping::API.new("a3969e3048c0f68d28fc1e7930a27067")
beer.find_by_name("ddee") # OR beer.find_by_name("Pub Name")

beer.locations.each do |location|
  # Standard data
  puts location.name # Pub name
  puts location.city
  puts location.state

  # Geo Data
  puts location.geo.lng # Geo lontitude
  puts location.geo.lat # Geo Latitude

  # Rating Data
  puts location.ratings.service
  puts location.ratings.selection
  puts location.ratings.overall

  # Related Images
  location.images.each do |image|

  end
end

# put your own credentials here
account_sid = 'AC31ffdb1a182e4458bc4ba498abe5a36a'
auth_token = 'ff8e6fc947fb411e18869d5bae57131a'

# set up a client to talk to the Twilio REST API
@client = Twilio::REST::Client.new account_sid, auth_token

@client.account.sms.messages.create(
  :from => '+14155992671',
  :to => '+17037894438',
  :body => 'Hey there!'
)  



  end

  # GET /beermaps/1
  # GET /beermaps/1.json
  def show
    @beermap = Beermap.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beermap }
    end
  end

  # GET /beermaps/new
  # GET /beermaps/new.json
  def new
    @beermap = Beermap.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beermap }
    end
  end

  # GET /beermaps/1/edit
  def edit
    @beermap = Beermap.find(params[:id])
  end

  # POST /beermaps
  # POST /beermaps.json
  def create
    @beermap = Beermap.new(params[:beermap])

    respond_to do |format|
      if @beermap.save
        format.html { redirect_to @beermap, notice: 'Beermap was successfully created.' }
        format.json { render json: @beermap, status: :created, location: @beermap }
      else
        format.html { render action: "new" }
        format.json { render json: @beermap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beermaps/1
  # PUT /beermaps/1.json
  def update
    @beermap = Beermap.find(params[:id])

    respond_to do |format|
      if @beermap.update_attributes(params[:beermap])
        format.html { redirect_to @beermap, notice: 'Beermap was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beermap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beermaps/1
  # DELETE /beermaps/1.json
  def destroy
    @beermap = Beermap.find(params[:id])
    @beermap.destroy

    respond_to do |format|
      format.html { redirect_to beermaps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beermaps_helper.rb
module BeermapsHelper
end

app/helpers/email_helper.rb
module EmailHelper
  
def sendemail (receiver, subject, body, file_path)
    
gmail = Gmail.connect(GMAIL_CONNECT_USER, GMAIL_CONNECT_PASS)
# play with your gmail...

 gmail.deliver do
  to receiver
  subject subject
  text_part do
    body body
  end
  html_part do
    content_type 'text/html; charset=UTF-8'
    body body
  end
  if (!file_path.nil?)
  add_file file_path
  end
 gmail.logout
end

end

end

app/views/beermaps/_form.html.erb
<%= form_for(@beermap) do |f| %>
  <% if @beermap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beermap.errors.count, "error") %> prohibited this beermap from being saved:</h2>

      <ul>
      <% @beermap.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :search_text %><br />
    <%= f.text_field :search_text %>
  </div>
  <div class="field">
    <%= f.label :phone_no %><br />
    <%= f.text_field :phone_no %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :connect %><br />
    <%= f.text_field :connect %>
  </div>
  <div class="field">
    <%= f.label :fackbook_friend %><br />
    <%= f.text_field :fackbook_friend %>
  </div>
  <div class="field">
    <%= f.label :extra %><br />
    <%= f.text_field :extra %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beermaps/edit.html.erb
<h1>Editing beermap</h1>

<%= render 'form' %>

<%= link_to 'Show', @beermap %> |
<%= link_to 'Back', beermaps_path %>

app/views/beermaps/index.html.erb
<h1>Listing beermaps</h1>

<table>
  <tr>
    <th>Search text</th>
    <th>Phone no</th>
    <th>Message</th>
    <th>Connect</th>
    <th>Fackbook friend</th>
    <th>Extra</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<!--<%= sendemail("mrvikas18@yahoo.com", "ee", "ee", nil)%>-->
<% @beermaps.each do |beermap| %>
  <tr>
    <td><%= beermap.search_text %></td>
    <td><%= beermap.phone_no %></td>
    <td><%= beermap.message %></td>
    <td><%= beermap.connect %></td>
    <td><%= beermap.fackbook_friend %></td>
    <td><%= beermap.extra %></td>
    <td><%= link_to 'Show', beermap %></td>
    <td><%= link_to 'Edit', edit_beermap_path(beermap) %></td>
    <td><%= link_to 'Destroy', beermap, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beermap', new_beermap_path %>

app/views/beermaps/new.html.erb
<h1>New beermap</h1>

<%= render 'form' %>

<%= link_to 'Back', beermaps_path %>

app/views/beermaps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Search text:</b>
  <%= @beermap.search_text %>
</p>

<p>
  <b>Phone no:</b>
  <%= @beermap.phone_no %>
</p>

<p>
  <b>Message:</b>
  <%= @beermap.message %>
</p>

<p>
  <b>Connect:</b>
  <%= @beermap.connect %>
</p>

<p>
  <b>Fackbook friend:</b>
  <%= @beermap.fackbook_friend %>
</p>

<p>
  <b>Extra:</b>
  <%= @beermap.extra %>
</p>


<%= link_to 'Edit', edit_beermap_path(@beermap) %> |
<%= link_to 'Back', beermaps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DebugApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>